In [1]:
import numpy as np
import sklearn 
from sklearn import model_selection, linear_model, naive_bayes
import matplotlib.pyplot
import re
import collections
import math

In [2]:
import pandas as pd

In [3]:
email_data = pd.read_csv(r"C:\Users\susan\Videos\archive (2)\spam_ham_dataset.csv")

In [4]:
email_data

Unnamed: 0 label                                               text  \
0            605   ham  Subject: enron methanol ; meter # : 988291\r\n...   
1           2349   ham  Subject: hpl nom for january 9 , 2001\r\n( see...   
2           3624   ham  Subject: neon retreat\r\nho ho ho , we ' re ar...   
3           4685  spam  Subject: photoshop , windows , office . cheap ...   
4           2030   ham  Subject: re : indian springs\r\nthis deal is t...   
...          ...   ...                                                ...   
5166        1518   ham  Subject: put the 10 on the ft\r\nthe transport...   
5167         404   ham  Subject: 3 / 4 / 2000 and following noms\r\nhp...   
5168        2933   ham  Subject: calpine daily gas nomination\r\n>\r\n...   
5169        1409   ham  Subject: industrial worksheets for august 2000...   
5170        4807  spam  Subject: important online banking alert\r\ndea...   

      label_num  
0             0  
1             0  
2             0  
3             1  
4             0  
...         ...  
5166          0  
5167          0  
5168          0  
5169          0  
5170          1  

[5171 rows x 4 columns]

In [5]:
email_text = email_data['text']

In [6]:
y = email_data['label_num'].to_numpy()

In [7]:
from sklearn.feature_extraction.text import CountVectorizer

In [8]:
countVec = CountVectorizer()
X_data = countVec.fit_transform(email_text)

In [9]:
X_train, X_test, Y_train, Y_test = model_selection.train_test_split(X_data, y)

In [10]:
def prob_class(y):
    c1_arr = np.where(y == 1)
    c1 = len(c1_arr[0])
    pc1 = c1/len(y)
    pc0 = 1-pc1
    return [pc0, pc1]

In [11]:
pc = prob_class(Y_train)

In [12]:
X_word_tr = X_train.T

In [13]:
M,N = X_train.shape
pc_mat = np.zeros((2,N))
s_count,ns_count = (0,0)

for y in range(len(Y_train)):
    if Y_train[y] == 1:
        old_s_count = s_count
        s_count += 1
        pc_mat[1,:] = (old_s_count * pc_mat[1,:] + X_train[y])/s_count

    if Y_train[y] == 0:
        old_ns_count = ns_count
        ns_count += 1
        pc_mat[0,:] = (old_ns_count * pc_mat[0,:] +X_train[y])/ns_count

In [14]:
def multiNB(X):
    y_pred = []
    X = X.toarray()
    print(X)
    for email in X:
        eml = np.where(email > 0)
        n = len(eml[0])
        log_term = math.log(math.factorial(n)) - sum(math.log(math.factorial(xi)) for xi in email)
        log_prob_sum0 = sum(xi * math.log(pi) for xi, pi in zip(email, pc_mat[0,:]) if pi > 0)
        log_prob_sum1 = sum(xi * math.log(pi) for xi, pi in zip(email, pc_mat[1,:]) if pi > 0)
        lp0 = log_term + log_prob_sum0 + math.log(pc[0])
        lp1 = log_term + log_prob_sum1 + math.log(pc[1])
        y_pred.append(1 if lp0 < lp1 else 0)
    return y_pred

In [15]:
y_pred = multiNB(X_test)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 2 0 ... 0 0 0]]


In [16]:
accuracy = sklearn.metrics.accuracy_score(Y_test, y_pred)
print(f'Accuracy of Custom Multinomial NB: {accuracy}')

Accuracy of Custom Multinomial NB: 0.6179427687548337


In [17]:
multinlNB = naive_bayes.MultinomialNB()

In [18]:
multinlNB.fit(X_train, Y_train)

MultinomialNB()

In [19]:
y_prdMNB = multinlNB.predict(X_test)
accuracyLib = sklearn.metrics.accuracy_score(Y_test, y_prdMNB)

In [20]:
accuracyLib

0.9837587006960556